refactor:  add gender selection and fetcher class
dosenk/rsclone pull request #119
Opened 2021-01-26 14:29 UTC by vladislavgribkov

2021-01-26 14:35 UTC, dosenk approved these changes

2021-01-27 15:00 UTC, KrohNic requested changes

2021-01-27 15:00 UTC, KrohNic commented on src/Components/Game/index.Game.ts
> +      this.stats.drawWordsNum += 1;
Это будет работать неправильно т.к. renderGameElements() вызывается при каждом возвращении в /game c других роутов и при смене языка.

2021-01-27 15:00 UTC, KrohNic commented on src/Components/Game/index.Game.ts
> +    this.stats.gameCount += 1;
Это будет работать неправильно т.к. renderGameElements() вызывается при каждом возвращении в /game c других роутов и при смене языка.

2021-01-27 15:00 UTC, KrohNic commented on src/Components/Game/index.Game.ts
> +        this.updateStatisticsInTheDatabase();
Это же можно сделать сразу на сервере. Наверное, даже проще получится.

2021-01-27 15:00 UTC, KrohNic commented on src/LangDictionaries/en.ts
> +  STATISTIC: 'In game (d.)/Drawn words/Guess the word/Number of games',
Guess the word - надо заменить на Words guessed

2021-01-27 15:01 UTC, dosenk approved these changes

2021-01-27 15:21 UTC, vladislavgribkov commented on src/Components/Game/index.Game.ts
> +      this.stats.drawWordsNum += 1;
Завтра допелю, я уже понял, где это вставить

2021-01-28 08:19 UTC, KrohNic approved these changes

2021-01-28 08:20 UTC, merged