Styles
dosenk/rsclone pull request #128
Opened 2021-02-01 16:44 UTC by dosenk

2021-02-01 17:12 UTC, vladislavgribkov approved these changes

2021-02-01 17:36 UTC, KrohNic requested changes

2021-02-01 17:36 UTC, KrohNic commented on src/Components/Game/GameEvents/GuessWord/index.GameGuessWord.scss
>  .guess-word {
можно добавить 
    pointer-events: none;
слово станет "прозрачным" для кликов. А то сейчас оно мешает рисованию.

2021-02-01 17:36 UTC, KrohNic commented on src/Components/Game/game.scss
> +.game {
Может адаптивности еще добавить? Хотя бы на ширине 500px чтобы норм отображалось?

2021-02-02 18:48 UTC, KrohNic approved these changes

2021-02-02 18:53 UTC, KrohNic approved these changes

2021-02-02 18:53 UTC, merged