feat: complited board class for the host and the player
dosenk/rsclone pull request #20
Opened 2020-12-29 16:10 UTC by vladislavgribkov

2020-12-29 17:44 UTC, KrohNic requested changes

2020-12-29 17:44 UTC, KrohNic commented on src/Components/App/board.scss
> +  justify-content: space-around;
стили для body задаются в main.css
в board.scss  задаются стили касающиеся только board компонента

2020-12-29 17:44 UTC, KrohNic commented on src/Components/App/board.scss
> +  #board {
если можно использовать классовый селектор, то лучше использовать его

2020-12-29 17:44 UTC, KrohNic commented on src/index.ts
> +  board.start();
перенеси это в App

2020-12-29 17:44 UTC, KrohNic commented on src/Components/App/index.Board.ts
> +  private draw: boolean = false;
для этого можно было бы использовать state из компонента observer

2020-12-29 17:44 UTC, KrohNic commented on src/Components/App/index.Board.ts
> +  }
это тоже можно через observer сделать, добавив функции в  actionCreator

2020-12-30 17:44 UTC, KrohNic approved these changes

2021-01-05 13:08 UTC, dosenk commented on webpack.config.js
> +const MiniCssExtractPlugin = require("mini-css-extract-plugin");
установи себе eslint, в конфиге airbnb-typescript/base ковычки должны быть одинарные

2021-01-06 12:26 UTC, KrohNic approved these changes

2021-01-06 12:26 UTC, KrohNic commented on src/index.ts
> +  board.startListener();
это в App перенеси

2021-01-06 12:52 UTC, dosenk approved these changes

2021-01-06 12:52 UTC, merged