feat: complited Panel class
dosenk/rsclone pull request #29
Opened 2021-01-06 20:46 UTC by vladislavgribkov

Осталось настроить общение через observer.

2021-01-06 21:27 UTC, KrohNic requested changes

2021-01-06 21:27 UTC, KrohNic commented on src/Components/App/index.Panel.ts
> +    document.body.append(this.panel);
В App есть mainElement. Принимай его в конструкторе и добавляй this.panel к нему.

2021-01-07 06:13 UTC, vladislavgribkov commented on src/Components/App/index.Panel.ts
> +    document.body.append(this.panel);
ok

2021-01-07 09:17 UTC, KrohNic approved these changes

2021-01-08 14:20 UTC, dosenk approved these changes

2021-01-08 14:31 UTC, merged